import { NextResponse } from 'next/server'
import { readFileSync, existsSync } from 'fs'
import { join } from 'path'
import { getCartridge } from '@/lib/cartridge-scanner'
import type { CartridgeManifest } from '@/lib/cartridge-scanner'
import { createCartridgeInstallPr } from '@/lib/github/cartridge-pr'
import { generateAppsInsertSql } from '@/lib/github/apps-insert'

/**
 * Web Studio → AppHarbor 本番リポに「カートリッジ install PR」を作成する。
 *
 * 必要な環境変数:
 *   GITHUB_TOKEN              : write 権限あり (repo スコープの classic PAT)
 *   APPHARBOR_TARGET_REPO     : "owner/repo" (デフォルト: "Tori-Take/appharbor")
 *   APPHARBOR_TARGET_BRANCH   : ベースブランチ (デフォルト: "main")
 *
 * カートリッジ側の registry エントリ (Studio の cartridges-registry.yaml) から
 * GitHub リポを特定する。
 */
export async function POST(
  _req: Request,
  { params }: { params: Promise<{ appId: string }> },
) {
  const { appId } = await params
  const safe = appId.replace(/[^a-zA-Z0-9_-]/g, '')

  const token = process.env.GITHUB_TOKEN
  if (!token) {
    return NextResponse.json(
      { ok: false, error: 'GITHUB_TOKEN が未設定です。Vercel の Environment Variables に repo スコープ付きの classic PAT を設定してください。' },
      { status: 400 },
    )
  }

  const targetRepo   = process.env.APPHARBOR_TARGET_REPO   ?? 'Tori-Take/appharbor'
  const targetBranch = process.env.APPHARBOR_TARGET_BRANCH ?? 'main'

  // カートリッジ情報取得
  const entry = getCartridge(safe)
  if (!entry) {
    return NextResponse.json({ ok: false, error: `cartridge ${safe} not found` }, { status: 404 })
  }

  const version = (entry.manifest?.version as string | undefined) ?? '0.1.0'

  // ソースリポを registry から特定
  const cartridgeRepo = findCartridgeRepo(safe)
  if (!cartridgeRepo) {
    return NextResponse.json(
      { ok: false, error: `Studio の registry に installed エントリ + repo フィールドが必要です: ${safe}` },
      { status: 400 },
    )
  }

  // Migration SQL を生成 (stage5-prepare と同じロジック)
  const schemaPath = join(entry.path, 'db', 'schema.sql')
  if (!existsSync(schemaPath)) {
    return NextResponse.json(
      { ok: false, error: `db/schema.sql が見つかりません: ${schemaPath}` },
      { status: 400 },
    )
  }
  const schemaSql = readFileSync(schemaPath, 'utf-8')
  const migrationSql = generateProductionMigration(safe, schemaSql, version, cartridgeRepo, entry.manifest)

  // PR 作成
  try {
    const result = await createCartridgeInstallPr(token, {
      cartridgeRepo,
      cartridgeRef: 'main',
      targetRepo,
      targetBase: targetBranch,
      cartridgeId: safe,
      version,
      migrationSql,
    })
    return NextResponse.json({ ok: true, ...result })
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e)
    return NextResponse.json({ ok: false, error: msg }, { status: 500 })
  }
}

const REGISTRY_PATH = join(process.cwd(), 'cartridges-registry.yaml')

/** Studio の registry から指定 cartridgeId の repo フィールドを取得 */
function findCartridgeRepo(cartridgeId: string): string | null {
  if (!existsSync(REGISTRY_PATH)) return null
  const text = readFileSync(REGISTRY_PATH, 'utf-8')
  let currentId: string | null = null
  let currentRepo: string | null = null
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.replace(/#.*$/, '').trimEnd()
    if (!line.trim()) continue
    const idMatch = line.match(/^\s+- id:\s*(.+)$/)
    if (idMatch) {
      if (currentId === cartridgeId && currentRepo) return currentRepo
      currentId = idMatch[1].trim()
      currentRepo = null
      continue
    }
    const repoMatch = line.match(/^\s+repo:\s*(.+)$/)
    if (repoMatch) currentRepo = repoMatch[1].trim()
  }
  if (currentId === cartridgeId && currentRepo) return currentRepo
  return null
}

/** カートリッジの schema.sql から本番用 migration SQL を生成 */
function generateProductionMigration(
  cartridgeId: string,
  schemaSql: string,
  version: string,
  sourceRepo: string,
  manifest: CartridgeManifest | null,
): string {
  const ts = new Date().toISOString()
  let sql = ''
  sql += `-- Auto-generated by AppHarbor Studio (install-to-appharbor)\n`
  sql += `-- cartridge: ${cartridgeId}\n`
  sql += `-- version:   ${version}\n`
  sql += `-- source:    https://github.com/${sourceRepo}/blob/main/db/schema.sql\n`
  sql += `-- generated: ${ts}\n\n`
  // studio スキーマ参照を除去 (本番は public スキーマ)
  const cleaned = schemaSql
    .replace(/create\s+schema\s+if\s+not\s+exists\s+studio\s*;/gi, '')
    .replace(/set\s+search_path\s+to\s+studio\s*,?\s*public\s*;/gi, '')
    .replace(/studio\./g, '')
  sql += cleaned.trim() + '\n\n'
  // apps テーブル登録
  if (manifest) {
    sql += generateAppsInsertSql(manifest)
  }
  return sql
}
